stages:
  - build_image
  - deploy


Build Image:
  stage: build_image
  image: docker
  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} -f Dockerfile .
    - docker images
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  
  only:
   - deploy-k8s

Deploy Staging:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1
  environment:
    name: eg-static-staging

  script:
    - kubectl get ns

  only:
   - deploy-k8s
