stages:
  - build_image
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest

  script:
    - sed -i "s#<DOCKER_IMAGE>#${DOCKER_IMAGE}#g" phytopathdb_deployment.yaml
    - kubectl apply -f phytopathdb_deployment.yaml

Build Image:
  stage: build_image
  image: docker
  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} -f Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  
  only:
   - master

Live:WP41-HX:
  extends: .deploy
  environment:
    name: wp41-hx-static
  only:
   - master

Live:WP40-HL:
  extends: .deploy
  environment:
    name: wp40-hl-static
  only:
   - master