stages:
  - build_image
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
    - sed -i "s/<CI_PROJECT_PATH_SLUG>/${CI_PROJECT_PATH_SLUG}/g" phytopathdb_deployment.yaml
    - sed -i "s/<CI_ENVIRONMENT_SLUG>/${CI_ENVIRONMENT_SLUG}/g" phytopathdb_deployment.yaml
    - sed -i "s#<DOCKER_IMAGE>#${DOCKER_IMAGE}#g" phytopathdb_deployment.yaml
    - kubectl apply -f phytopathdb_deployment.yaml

Build Image:
  stage: build_image
  image: docker
  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} -f Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  
  only:
   - master

Live:EHK:
  extends: .deploy
  environment:
    name: eg-static-staging
  only:
   - master

Live:WP-HX:
  extends: .deploy
  environment:
    name: wp-hx-eg-static
  only:
   - master

Live:WP-HH:
  extends: .deploy
  environment:
    name: wp-hh-eg-static
  only:
   - master