stages:
  - build_image
  - deploy


Build Image:
  stage: build_image
  image: docker

  script:
    - docker build -t phytopathdb:${CI_COMMIT_REF_NAME} -f Dockerfile
    - docker push phytopathdb:${CI_COMMIT_REF_NAME}
  
  only:
  - deploy-k8s

Deploy Staging:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1
  environment:
    name: eg-static-staging

  script:
    - kubectl get ns

  only:
  - deploy-k8s
