apiVersion: v1
kind: Service
metadata:
  name:  phytopathdb-svc
  labels:
     ensembl.web.app.name: phytopathdb
spec:
  selector:
     ensembl.web.app.name: phytopathdb
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
