apiVersion: v1
kind: Service
metadata:
  name: phytopathdb-svc
  labels:
    app: phytopathdb-svc
spec:
  selector:
    app: phytopathdb
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80